Add Queue Recipe
bonifaido/rust-zookeeper pull request #80
Opened 2021-02-07 16:53 UTC by volfco

2021-02-07 17:24 UTC, volfco commented
Reverted clippy. Was going to do that in a different PR

2021-02-08 16:24 UTC, bonifaido requested changes
Could you please fix the warnings around unused code parts?

2021-02-12 18:10 UTC, volfco commented
@bonifaido Done. Sorry for the delay

2021-02-16 08:34 UTC, bonifaido approved these changes
Great stuff!

2021-02-16 08:35 UTC, merged